{{- if .Values.secrets.serverCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.serverCredentials.name }}
data:
  password: "{{ .Values.secrets.serverCredentials.password | b64enc }}"
  adminPassword: "{{ .Values.secrets.serverCredentials.adminPassword | required ".Values.secrets.serverCredentials.adminPassword is required" | b64enc }}"
  commandPassword: "{{ .Values.secrets.serverCredentials.commandPassword | required ".Values.secrets.steamCredentials.commandPassword is required" | b64enc }}"
{{- end }}
