{{- if .Values.secrets.steamCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.steamCredentials.name }}
data:
  username: {{ .Values.secrets.steamCredentials.username | required ".Values.secrets.steamCredentials.username is required" | b64enc }}
  password: {{ .Values.secrets.steamCredentials.password | required ".Values.secrets.steamCredentials.password is required" | b64enc }}
{{- end }}
