{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $k, $v := .Values.service.udpPortMap }}
    - name: udp-{{ $k }}-{{ $v }}
      port: {{ $k }}
      targetPort: {{ $v }}
      protocol: UDP
  {{- end }}
  {{- with .Values.service.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
